-- Migration: Create appointments, medications, and medical_records tables
-- Created: 2026-01-29
-- SUPERSEDED: These tables were removed in migration 022 as they were never used.
--             The real appointment system uses the `bookings` + `services` tables.
--             This migration is kept as a no-op so migration numbering stays intact.
